This notebook is a little touch on working with PyTorch Tensor, following the tutorial here: <a href="https://pytorch.org/tutorials/beginner/blitz/tensor_tutorial.html#sphx-glr-beginner-blitz-tensor-tutorial-py">What is PyTorch?</a>

In [1]:
from __future__ import print_function
import torch

In [15]:
# Contruct an uninitialized 5x3 matrix
x = torch.empty(5, 3)
# x = torch.empty(5, 3, dtype=torch.int64)
print(x)

tensor([[9.2755e-39, 1.0561e-38, 6.8878e-39],
        [1.0837e-38, 1.0102e-38, 4.2246e-39],
        [1.0286e-38, 1.0653e-38, 1.0194e-38],
        [8.4490e-39, 1.0469e-38, 9.3674e-39],
        [9.9184e-39, 8.7245e-39, 9.2755e-39]])


In [19]:
# Construct an initilized 5x3 matrix
x = torch.rand(5, 3)
print(x)

tensor([[0.3810, 0.9616, 0.9831],
        [0.6184, 0.5403, 0.6878],
        [0.2406, 0.1913, 0.5531],
        [0.9684, 0.8206, 0.0284],
        [0.4755, 0.7826, 0.0172]])


Notes:
<ul>
    <li> .empty() - constructs an uninitialized NxN matrix of dtype (if given)</li>
    <li> .rand() - constructs a randomly initialized NxN matrix</li>
</ul>

In [20]:
x = torch.zeros(5, 3)
print(x)

tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]])


In [23]:
x = torch.zeros(5, 3, dtype=torch.int64)
print(x)

tensor([[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]])


Notes:
<ul>
    <li> .zeros() - constructs an initialized NxN matrix of 0's; default dtype to global default (i.e. float64), but can be changed if specified</li>
</ul>

In [24]:
x = torch.tensor([5.5, 3])
print(x)

tensor([5.5000, 3.0000])


In [25]:
x = x.new_ones(5, 3, dtype=torch.double)      # new_* methods take in sizes
print(x)

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]], dtype=torch.float64)


In [26]:
x = torch.randn_like(x, dtype=torch.float)    # override dtype!
print(x)                                      # result has the same size

tensor([[-1.3653,  0.6669, -1.9069],
        [ 1.6064, -3.1018,  2.1661],
        [ 0.6015, -1.7839,  1.3271],
        [ 1.8847, -0.0958, -0.7776],
        [-0.7761, -0.2081,  0.7042]])


In [27]:
print(x.size())

torch.Size([5, 3])


In [30]:
y = torch.rand(5, 3)
print(y)

tensor([[0.3045, 0.3193, 0.0275],
        [0.4045, 0.8638, 0.1767],
        [0.7943, 0.1317, 0.7260],
        [0.0966, 0.5261, 0.0522],
        [0.5347, 0.0928, 0.2366]])


In [31]:
# Output tensor as an argument
result = torch.empty(5, 3)
torch.add(x, y, out=result)
print(result)

tensor([[-1.0608,  0.9862, -1.8794],
        [ 2.0109, -2.2380,  2.3427],
        [ 1.3958, -1.6522,  2.0531],
        [ 1.9812,  0.4302, -0.7254],
        [-0.2414, -0.1153,  0.9408]])


In [32]:
# In-place addition
y.add_(x)
print(y)

tensor([[-1.0608,  0.9862, -1.8794],
        [ 2.0109, -2.2380,  2.3427],
        [ 1.3958, -1.6522,  2.0531],
        [ 1.9812,  0.4302, -0.7254],
        [-0.2414, -0.1153,  0.9408]])


In [41]:
print(x[:, 0])

tensor([ 1.4946, -0.5142, -0.9923, -1.4150])


In [38]:
print(x[0][0])

tensor(1.4946)

We can use standard NumPy-like indexing.

In [34]:
x = torch.randn(4, 4)

# Resizing/reshaping tensor
y = x.view(16)
z = x.view(-1, 8)  # the size -1 is inferred from other dimensions
print(x.size(), y.size(), z.size())

torch.Size([4, 4]) torch.Size([16]) torch.Size([2, 8])


Notes:
<ul>
    <li> .view() - resize/reshape tensor by given params</li>
</ul>

In [42]:
# Use item() to get value from 1-item tensor
x = torch.randn(1)
print(x)
print(x.item())

tensor([0.0982])
0.09822846204042435


In [43]:
a = torch.ones(5)

# Use numpy() to convert Torch Tensor to Numpy array
b = a.numpy()
print(b)

[1. 1. 1. 1. 1.]


In [45]:
a.add_(1)
print(a)
print(b)

tensor([2., 2., 2., 2., 2.])
[2. 2. 2. 2. 2.]


In [52]:
c = torch.ones(5)
c.copy_(a)
c.add_(1)
print(c)
print(a)

tensor([3., 3., 3., 3., 3.])
tensor([2., 2., 2., 2., 2.])


In [53]:
import numpy as np

a = np.ones(5)
b = torch.from_numpy(a)

np.add(a, 1, out=a)
print(a)
print(b)

[2. 2. 2. 2. 2.]
tensor([2., 2., 2., 2., 2.], dtype=torch.float64)


In [54]:
# let us run this cell only if CUDA is available
# We will use ``torch.device`` objects to move tensors in and out of GPU
if torch.cuda.is_available():
    device = torch.device("cuda")          # a CUDA device object
    y = torch.ones_like(x, device=device)  # directly create a tensor on GPU
    x = x.to(device)                       # or just use strings ``.to("cuda")``
    z = x + y
    print(z)
    print(z.to("cpu", torch.double))       # ``.to`` can also change dtype together!

tensor([1.0982], device='cuda:0')
tensor([1.0982], dtype=torch.float64)
